services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: pool
      POSTGRES_PASSWORD: pool
      POSTGRES_DB: pool
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pool"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"