name: Upload to S3

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Update config
        env:
          CONFIG_PATH: frontend/public/assets/config.json
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          SOCKET_URL: ${{ secrets.BACKEND_URL }}
        run: | 
          cat << EOF > $CONFIG_PATH
          {
            "API_URL": "${BACKEND_URL}",
            "SOCKET_URL": "${SOCKET_URL}"
          }
          EOF

      - name: Build Angular app
        working-directory: frontend
        run: npm run build -- --configuration=production

      - name: Sync to S3
        uses: Noelware/s3-action@2
        with:
          directories: |
              ./frontend/dist/frontend/browser

          access-key-id: ${{ secrets.AWS_KEY_ID }}
          secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.AWS_BUCKET }}
          object-acl: ''