name: Upload to S3

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Update config
        env:
          CONFIG_PATH: frontend/public/assets/config.json
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          SOCKET_URL: ${{ secrets.BACKEND_URL }}
        run: | 
          cat << EOF > $CONFIG_PATH
          {
            "API_URL": "${BACKEND_URL}",
            "SOCKET_URL": "${SOCKET_URL}"
          }
          EOF

      - name: Build Angular app
        working-directory: frontend
        run: npm run build -- --configuration=production

      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'frontend/dist/frontend/browser'